language: objective-c
before_install:
    - brew update
script: xcodebuild -project ABPadLockScreenDemo/ABPadLockScreenDemo.xcodeproj -scheme ABPadLockScreenDemo -sdk iphonesimulator -destination 'name=iPhone 5' build test